### ISSUE TITLE
Field within quotes with comma breaks parsing

### ISSUE THREAD

**Issue by kennymalac** [apahl/csvtable#1]
Hello, I am parsing a CSV with a comma in a string field:
16,AS,ASM,16,60.0,,-14.270999999999999,"American Samoa, US",2020-01-22,0,-170.132,US,American Samoa  
  
Such a string gives me an error when looping over the CSV:
/home/kenster/.nimble/pkgs/csvtable-0.3.0/csvtable.nim(90) csvparser
/home/kenster/.choosenim/toolchains/nim-1.0.6/lib/system/fatal.nim(39) sysFatal
Error: unhandled exception: index 13 not in 0 .. 12 [IndexError]

**Comment by apahl** [comment]
Yay, first issue! Thanks for trying this project.

This is a very simple implementation of a CSV parser and quoted strings are currently not supported.  
I'll add a comment to the README.

Kind regards,  
Axel
